{{- if or (and (not .Values.elasticsearch.password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana.fullname" . }}
  namespace: {{ template "kibana.namespace" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.elasticsearch.password) }}
  kibana-password: {{ .Values.elasticsearch.password | b64enc | quote }}
  {{- else }}
  kibana-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}
