{{- if .Values.envRenderSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana.fullname" . }}-env
  namespace: {{ template "kibana.namespace" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.envRenderSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end }}
