apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.bioextractor.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.bioextractor.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  {{ $podconfig := .Values.services.bioextractor.podconfig }}
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.bioextractor.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.bioextractor.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.bioextractor.serviceName }} 
        image: {{ .Values.services.bioextractor.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: extraction_format_env
          value: {{ .Values.extraction_format }}
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: mosip_biosdk_service
          value: {{ .Values.biosdkServiceUrl }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - containerPort: {{ .Values.services.bioextractor.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

        readinessProbe:
          httpGet:
            path: {{ .Values.services.bioextractor.healthUrl }} 
            port: {{ .Values.services.bioextractor.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
 #       livenessProbe:
 #         httpGet:
 #           path: {{ .Values.services.bioextractor.healthUrl }} 
 #           port: {{ .Values.services.bioextractor.containerPort }} 
 #         initialDelaySeconds: {{ .Values.probe.initialDelay }} 
 #         periodSeconds: {{ .Values.probe.period }}
 #
      {{- include "logger.sidecar" .  | indent 6}}

      {{- include "logger.volume" .  | indent 6}}
